[package]
name = "ota-serverd"
description = "The ai-ota delivery server binary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords = ["ota", "server"]
categories = ["network-programming"]

[lints]
workspace = true