[package]
name = "ota-api"
description = "Shared API contract types between agent, server and CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords = ["ota", "api"]
categories = ["network-programming"]

[lints]
workspace = true